version: '2'
services:
  nginx:
    container_name: nginx
    image: nginx:1.12-alpine
    ports:
      - "8443:443"
    volumes:
      - "./server.key:/etc/nginx/server.key:ro"
      - "./server.crt:/etc/nginx/server.crt:ro"
      - "./default.conf:/etc/nginx/conf.d/default.conf:ro"